/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateCollectionEventInput = {
  chain?: string | null,
  source?: string | null,
  collection_address?: string | null,
  event_id?: string | null,
  token_id?: string | null,
  event_type?: string | null,
  timestamp?: number | null,
  auction_type?: string | null,
  price?: string | null,
  start_time?: number | null,
  end_time?: number | null,
  payment_symbol?: string | null,
  from_address?: string | null,
  to_address?: string | null,
  hash?: string | null,
  total_price?: string | null,
  starting_price?: string | null,
  ending_price?: string | null,
};

export type CollectionEvent = {
  __typename: "CollectionEvent",
  chain?: string | null,
  source?: string | null,
  collection_address?: string | null,
  token_id?: string | null,
  event_type?: string | null,
  timestamp?: number | null,
  auction_type?: string | null,
  price?: string | null,
  start_time?: number | null,
  end_time?: number | null,
  payment_symbol?: string | null,
  from_address?: string | null,
  to_address?: string | null,
  hash?: string | null,
  total_price?: string | null,
  starting_price?: string | null,
  ending_price?: string | null,
};

export type CollectionEventConnection = {
  __typename: "CollectionEventConnection",
  items?:  Array<CollectionEvent | null > | null,
  nextToken?: string | null,
};

export type UserNFTConnection = {
  __typename: "UserNFTConnection",
  items?:  Array<UserNFT | null > | null,
  nextToken?: string | null,
  totalCount?: number | null,
};

export type UserNFT = {
  __typename: "UserNFT",
  title?: string | null,
  token_uri_gateway?: string | null,
  token_uri_raw?: string | null,
  updated_at?: string | null,
  name?: string | null,
  image?: string | null,
  attributes?: string | null,
  media?: string | null,
  description?: string | null,
  token_id?: string | null,
  token_type?: string | null,
  address?: string | null,
  balance?: number | null,
};

export type InterbullNFTConnection = {
  __typename: "InterbullNFTConnection",
  items?:  Array<InterbullNFT | null > | null,
  nextToken?: string | null,
  totalCount?: number | null,
};

export type InterbullNFT = {
  __typename: "InterbullNFT",
  title?: string | null,
  token_uri_gateway?: string | null,
  token_uri_raw?: string | null,
  updated_at?: string | null,
  name?: string | null,
  image?: string | null,
  attributes?: string | null,
  media?: string | null,
  description?: string | null,
  token_id?: string | null,
  token_type?: string | null,
  address?: string | null,
  price?: number | null,
  payment_token?: string | null,
  listed?: boolean | null,
};

export type NFTConnection = {
  __typename: "NFTConnection",
  items?:  Array<NFT | null > | null,
  nextToken?: string | null,
};

export type NFT = {
  __typename: "NFT",
  title?: string | null,
  token_uri_gateway?: string | null,
  token_uri_raw?: string | null,
  updated_at?: string | null,
  name?: string | null,
  image?: string | null,
  attributes?: string | null,
  media?: string | null,
  description?: string | null,
  token_id?: string | null,
  token_type?: string | null,
  address?: string | null,
};

export type Collection = {
  __typename: "Collection",
  chain?: string | null,
  collection_address?: string | null,
  collection_logo?: string | null,
  collection_symbol?: string | null,
  contract_external_url?: string | null,
  created_date?: string | null,
  description?: string | null,
  discord_url?: string | null,
  featured_image_url?: string | null,
  instagram_username?: string | null,
  large_collection_logo?: string | null,
  looksrare_url?: string | null,
  name?: string | null,
  num_owners?: number | null,
  opensea_url?: string | null,
  project_website?: string | null,
  schema_name?: string | null,
  seven_day_average_price?: number | null,
  seven_day_change?: number | null,
  seven_day_sales?: number | null,
  seven_day_volume?: number | null,
  average_listing_price_eth_1d?: number | null,
  average_sale_price_eth_1d?: number | null,
  average_listing_price_pct_change_eth_1d?: number | null,
  average_sale_price_pct_change_eth_1d?: number | null,
  close_eth_1d?: number | null,
  high_eth_1d?: number | null,
  listing_count_1d?: number | null,
  listing_count_pct_change_1d?: number | null,
  low_eth_1d?: number | null,
  median_listing_price_eth_1d?: number | null,
  median_sale_price_eth_1d?: number | null,
  median_listing_price_pct_change_eth_1d?: number | null,
  median_sale_price_pct_change_eth_1d?: number | null,
  momentum_1d?: number | null,
  momentum_pct_change_1d?: number | null,
  open_eth_1d?: number | null,
  sale_count_1d?: number | null,
  sale_count_pct_change_1d?: number | null,
  unique_buyers_1d?: number | null,
  unique_listers_1d?: number | null,
  unique_sellers_1d?: number | null,
  unique_buyers_pct_change_1d?: number | null,
  unique_listers_pct_change_1d?: number | null,
  unique_sellers_pct_change_1d?: number | null,
  volume_eth_1d?: number | null,
  total_supply?: number | null,
  last_momentum?: number | null,
  twitter_username?: string | null,
  updated_at?: number | null,
};

export type CollectionConnection = {
  __typename: "CollectionConnection",
  items?:  Array<Collection | null > | null,
  nextToken?: string | null,
};

export type CreateCollectionEventMutationVariables = {
  input: CreateCollectionEventInput,
};

export type CreateCollectionEventMutation = {
  createCollectionEvent?:  {
    __typename: "CollectionEvent",
    chain?: string | null,
    source?: string | null,
    collection_address?: string | null,
    token_id?: string | null,
    event_type?: string | null,
    timestamp?: number | null,
    auction_type?: string | null,
    price?: string | null,
    start_time?: number | null,
    end_time?: number | null,
    payment_symbol?: string | null,
    from_address?: string | null,
    to_address?: string | null,
    hash?: string | null,
    total_price?: string | null,
    starting_price?: string | null,
    ending_price?: string | null,
  } | null,
};

export type QueryCollectionEventBySymbolQueryVariables = {
  collection_symbol: string,
  first?: number | null,
  after?: string | null,
};

export type QueryCollectionEventBySymbolQuery = {
  queryCollectionEventBySymbol?:  {
    __typename: "CollectionEventConnection",
    items?:  Array< {
      __typename: "CollectionEvent",
      chain?: string | null,
      source?: string | null,
      collection_address?: string | null,
      token_id?: string | null,
      event_type?: string | null,
      timestamp?: number | null,
      auction_type?: string | null,
      price?: string | null,
      start_time?: number | null,
      end_time?: number | null,
      payment_symbol?: string | null,
      from_address?: string | null,
      to_address?: string | null,
      hash?: string | null,
      total_price?: string | null,
      starting_price?: string | null,
      ending_price?: string | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type QueryCollectionEventsQueryVariables = {
  collection_address: string,
  chain: string,
  after?: string | null,
  first?: number | null,
};

export type QueryCollectionEventsQuery = {
  queryCollectionEvents?:  {
    __typename: "CollectionEventConnection",
    items?:  Array< {
      __typename: "CollectionEvent",
      chain?: string | null,
      source?: string | null,
      collection_address?: string | null,
      token_id?: string | null,
      event_type?: string | null,
      timestamp?: number | null,
      auction_type?: string | null,
      price?: string | null,
      start_time?: number | null,
      end_time?: number | null,
      payment_symbol?: string | null,
      from_address?: string | null,
      to_address?: string | null,
      hash?: string | null,
      total_price?: string | null,
      starting_price?: string | null,
      ending_price?: string | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type QueryUsersEthereumNFTsQueryVariables = {
  collection_address?: string | null,
  user_address?: string | null,
  after?: string | null,
};

export type QueryUsersEthereumNFTsQuery = {
  queryUsersEthereumNFTs?:  {
    __typename: "UserNFTConnection",
    items?:  Array< {
      __typename: "UserNFT",
      title?: string | null,
      token_uri_gateway?: string | null,
      token_uri_raw?: string | null,
      updated_at?: string | null,
      name?: string | null,
      image?: string | null,
      attributes?: string | null,
      media?: string | null,
      description?: string | null,
      token_id?: string | null,
      token_type?: string | null,
      address?: string | null,
      balance?: number | null,
    } | null > | null,
    nextToken?: string | null,
    totalCount?: number | null,
  } | null,
};

export type QueryInterbullNFTsQueryVariables = {
  collection_address?: string | null,
};

export type QueryInterbullNFTsQuery = {
  queryInterbullNFTs?:  {
    __typename: "InterbullNFTConnection",
    items?:  Array< {
      __typename: "InterbullNFT",
      title?: string | null,
      token_uri_gateway?: string | null,
      token_uri_raw?: string | null,
      updated_at?: string | null,
      name?: string | null,
      image?: string | null,
      attributes?: string | null,
      media?: string | null,
      description?: string | null,
      token_id?: string | null,
      token_type?: string | null,
      address?: string | null,
      price?: number | null,
      payment_token?: string | null,
      listed?: boolean | null,
    } | null > | null,
    nextToken?: string | null,
    totalCount?: number | null,
  } | null,
};

export type QueryEthereumNFTsQueryVariables = {
  collection_address: string,
  after?: string | null,
  first?: number | null,
};

export type QueryEthereumNFTsQuery = {
  queryEthereumNFTs?:  {
    __typename: "NFTConnection",
    items?:  Array< {
      __typename: "NFT",
      title?: string | null,
      token_uri_gateway?: string | null,
      token_uri_raw?: string | null,
      updated_at?: string | null,
      name?: string | null,
      image?: string | null,
      attributes?: string | null,
      media?: string | null,
      description?: string | null,
      token_id?: string | null,
      token_type?: string | null,
      address?: string | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type GetCollectionByCollectionSymbolQueryVariables = {
  collection_symbol?: string | null,
};

export type GetCollectionByCollectionSymbolQuery = {
  getCollectionByCollectionSymbol?:  {
    __typename: "Collection",
    chain?: string | null,
    collection_address?: string | null,
    collection_logo?: string | null,
    collection_symbol?: string | null,
    contract_external_url?: string | null,
    created_date?: string | null,
    description?: string | null,
    discord_url?: string | null,
    featured_image_url?: string | null,
    instagram_username?: string | null,
    large_collection_logo?: string | null,
    looksrare_url?: string | null,
    name?: string | null,
    num_owners?: number | null,
    opensea_url?: string | null,
    project_website?: string | null,
    schema_name?: string | null,
    seven_day_average_price?: number | null,
    seven_day_change?: number | null,
    seven_day_sales?: number | null,
    seven_day_volume?: number | null,
    average_listing_price_eth_1d?: number | null,
    average_sale_price_eth_1d?: number | null,
    average_listing_price_pct_change_eth_1d?: number | null,
    average_sale_price_pct_change_eth_1d?: number | null,
    close_eth_1d?: number | null,
    high_eth_1d?: number | null,
    listing_count_1d?: number | null,
    listing_count_pct_change_1d?: number | null,
    low_eth_1d?: number | null,
    median_listing_price_eth_1d?: number | null,
    median_sale_price_eth_1d?: number | null,
    median_listing_price_pct_change_eth_1d?: number | null,
    median_sale_price_pct_change_eth_1d?: number | null,
    momentum_1d?: number | null,
    momentum_pct_change_1d?: number | null,
    open_eth_1d?: number | null,
    sale_count_1d?: number | null,
    sale_count_pct_change_1d?: number | null,
    unique_buyers_1d?: number | null,
    unique_listers_1d?: number | null,
    unique_sellers_1d?: number | null,
    unique_buyers_pct_change_1d?: number | null,
    unique_listers_pct_change_1d?: number | null,
    unique_sellers_pct_change_1d?: number | null,
    volume_eth_1d?: number | null,
    total_supply?: number | null,
    last_momentum?: number | null,
    twitter_username?: string | null,
    updated_at?: number | null,
  } | null,
};

export type QueryEthereumCollectionsBySevenDayVolumeQueryVariables = {
  first?: number | null,
  after?: string | null,
};

export type QueryEthereumCollectionsBySevenDayVolumeQuery = {
  queryEthereumCollectionsBySevenDayVolume?:  {
    __typename: "CollectionConnection",
    items?:  Array< {
      __typename: "Collection",
      chain?: string | null,
      collection_address?: string | null,
      collection_logo?: string | null,
      collection_symbol?: string | null,
      contract_external_url?: string | null,
      created_date?: string | null,
      description?: string | null,
      discord_url?: string | null,
      featured_image_url?: string | null,
      instagram_username?: string | null,
      large_collection_logo?: string | null,
      looksrare_url?: string | null,
      name?: string | null,
      num_owners?: number | null,
      opensea_url?: string | null,
      project_website?: string | null,
      schema_name?: string | null,
      seven_day_average_price?: number | null,
      seven_day_change?: number | null,
      seven_day_sales?: number | null,
      seven_day_volume?: number | null,
      average_listing_price_eth_1d?: number | null,
      average_sale_price_eth_1d?: number | null,
      average_listing_price_pct_change_eth_1d?: number | null,
      average_sale_price_pct_change_eth_1d?: number | null,
      close_eth_1d?: number | null,
      high_eth_1d?: number | null,
      listing_count_1d?: number | null,
      listing_count_pct_change_1d?: number | null,
      low_eth_1d?: number | null,
      median_listing_price_eth_1d?: number | null,
      median_sale_price_eth_1d?: number | null,
      median_listing_price_pct_change_eth_1d?: number | null,
      median_sale_price_pct_change_eth_1d?: number | null,
      momentum_1d?: number | null,
      momentum_pct_change_1d?: number | null,
      open_eth_1d?: number | null,
      sale_count_1d?: number | null,
      sale_count_pct_change_1d?: number | null,
      unique_buyers_1d?: number | null,
      unique_listers_1d?: number | null,
      unique_sellers_1d?: number | null,
      unique_buyers_pct_change_1d?: number | null,
      unique_listers_pct_change_1d?: number | null,
      unique_sellers_pct_change_1d?: number | null,
      volume_eth_1d?: number | null,
      total_supply?: number | null,
      last_momentum?: number | null,
      twitter_username?: string | null,
      updated_at?: number | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type SearchCollectionsQueryVariables = {
  query?: string | null,
};

export type SearchCollectionsQuery = {
  searchCollections?:  Array< {
    __typename: "Collection",
    chain?: string | null,
    collection_address?: string | null,
    collection_logo?: string | null,
    collection_symbol?: string | null,
    contract_external_url?: string | null,
    created_date?: string | null,
    description?: string | null,
    discord_url?: string | null,
    featured_image_url?: string | null,
    instagram_username?: string | null,
    large_collection_logo?: string | null,
    looksrare_url?: string | null,
    name?: string | null,
    num_owners?: number | null,
    opensea_url?: string | null,
    project_website?: string | null,
    schema_name?: string | null,
    seven_day_average_price?: number | null,
    seven_day_change?: number | null,
    seven_day_sales?: number | null,
    seven_day_volume?: number | null,
    average_listing_price_eth_1d?: number | null,
    average_sale_price_eth_1d?: number | null,
    average_listing_price_pct_change_eth_1d?: number | null,
    average_sale_price_pct_change_eth_1d?: number | null,
    close_eth_1d?: number | null,
    high_eth_1d?: number | null,
    listing_count_1d?: number | null,
    listing_count_pct_change_1d?: number | null,
    low_eth_1d?: number | null,
    median_listing_price_eth_1d?: number | null,
    median_sale_price_eth_1d?: number | null,
    median_listing_price_pct_change_eth_1d?: number | null,
    median_sale_price_pct_change_eth_1d?: number | null,
    momentum_1d?: number | null,
    momentum_pct_change_1d?: number | null,
    open_eth_1d?: number | null,
    sale_count_1d?: number | null,
    sale_count_pct_change_1d?: number | null,
    unique_buyers_1d?: number | null,
    unique_listers_1d?: number | null,
    unique_sellers_1d?: number | null,
    unique_buyers_pct_change_1d?: number | null,
    unique_listers_pct_change_1d?: number | null,
    unique_sellers_pct_change_1d?: number | null,
    volume_eth_1d?: number | null,
    total_supply?: number | null,
    last_momentum?: number | null,
    twitter_username?: string | null,
    updated_at?: number | null,
  } | null > | null,
};

export type GetCollectionsQueryVariables = {
  sort?: string | null,
  filters?: string | null,
  size?: number | null,
  from?: number | null,
};

export type GetCollectionsQuery = {
  getCollections?:  Array< {
    __typename: "Collection",
    chain?: string | null,
    collection_address?: string | null,
    collection_logo?: string | null,
    collection_symbol?: string | null,
    contract_external_url?: string | null,
    created_date?: string | null,
    description?: string | null,
    discord_url?: string | null,
    featured_image_url?: string | null,
    instagram_username?: string | null,
    large_collection_logo?: string | null,
    looksrare_url?: string | null,
    name?: string | null,
    num_owners?: number | null,
    opensea_url?: string | null,
    project_website?: string | null,
    schema_name?: string | null,
    seven_day_average_price?: number | null,
    seven_day_change?: number | null,
    seven_day_sales?: number | null,
    seven_day_volume?: number | null,
    average_listing_price_eth_1d?: number | null,
    average_sale_price_eth_1d?: number | null,
    average_listing_price_pct_change_eth_1d?: number | null,
    average_sale_price_pct_change_eth_1d?: number | null,
    close_eth_1d?: number | null,
    high_eth_1d?: number | null,
    listing_count_1d?: number | null,
    listing_count_pct_change_1d?: number | null,
    low_eth_1d?: number | null,
    median_listing_price_eth_1d?: number | null,
    median_sale_price_eth_1d?: number | null,
    median_listing_price_pct_change_eth_1d?: number | null,
    median_sale_price_pct_change_eth_1d?: number | null,
    momentum_1d?: number | null,
    momentum_pct_change_1d?: number | null,
    open_eth_1d?: number | null,
    sale_count_1d?: number | null,
    sale_count_pct_change_1d?: number | null,
    unique_buyers_1d?: number | null,
    unique_listers_1d?: number | null,
    unique_sellers_1d?: number | null,
    unique_buyers_pct_change_1d?: number | null,
    unique_listers_pct_change_1d?: number | null,
    unique_sellers_pct_change_1d?: number | null,
    volume_eth_1d?: number | null,
    total_supply?: number | null,
    last_momentum?: number | null,
    twitter_username?: string | null,
    updated_at?: number | null,
  } | null > | null,
};

export type OnCreateCollectionEventSubscriptionVariables = {
  collection_address?: string | null,
};

export type OnCreateCollectionEventSubscription = {
  onCreateCollectionEvent?:  {
    __typename: "CollectionEvent",
    chain?: string | null,
    source?: string | null,
    collection_address?: string | null,
    token_id?: string | null,
    event_type?: string | null,
    timestamp?: number | null,
    auction_type?: string | null,
    price?: string | null,
    start_time?: number | null,
    end_time?: number | null,
    payment_symbol?: string | null,
    from_address?: string | null,
    to_address?: string | null,
    hash?: string | null,
    total_price?: string | null,
    starting_price?: string | null,
    ending_price?: string | null,
  } | null,
};

export type OnEventSubscription = {
  onEvent?:  {
    __typename: "CollectionEvent",
    chain?: string | null,
    source?: string | null,
    collection_address?: string | null,
    token_id?: string | null,
    event_type?: string | null,
    timestamp?: number | null,
    auction_type?: string | null,
    price?: string | null,
    start_time?: number | null,
    end_time?: number | null,
    payment_symbol?: string | null,
    from_address?: string | null,
    to_address?: string | null,
    hash?: string | null,
    total_price?: string | null,
    starting_price?: string | null,
    ending_price?: string | null,
  } | null,
};
